# platform = multi_platform_ubuntu
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: "{{{ rule_title }}} - Ensure AIDE Is Installed"
  ansible.builtin.apt:
    name: aide
    state: present

- name: "{{{ rule_title }}} - Check if DB Path in {{{ aide_conf_path }}} Is Already Set"
  ansible.builtin.lineinfile:
    path: {{{ aide_conf_path }}}
    regexp: ^#?(\s*)(database=)(.*)$
    state: absent
  check_mode: true
  changed_when: false
  register: database_replace

- name: "{{{ rule_title }}} - Check if DB Out Path in {{{ aide_conf_path }}} Is Already Set"
  ansible.builtin.lineinfile:
    path: {{{ aide_conf_path }}}
    regexp: ^#?(\s*)(database_out=)(.*)$
    state: absent
  check_mode: true
  changed_when: false
  register: database_out_replace

- name: "{{{ rule_title }}} - Fix DB Path in Config File if Necessary"
  ansible.builtin.lineinfile:
    path: {{{ aide_conf_path }}}
    regexp: ^#?(\s*)(database)(\s*)=(\s*)(.*)$
    line: \2\3=\4file:{{{ aide_db_path }}}
    backrefs: true
  when: database_replace.found > 0

- name: "{{{ rule_title }}} - Fix DB Out Path in Config File if Necessary"
  ansible.builtin.lineinfile:
    path: {{{ aide_conf_path }}}
    regexp: ^#?(\s*)(database_out)(\s*)=(\s*)(.*)$
    line: \2\3=\4file:{{{ aide_db_new_path }}}
    backrefs: true
  when: database_out_replace.found > 0

- name: "{{{ rule_title }}} - Ensure the Default DB Path is Added"
  ansible.builtin.lineinfile:
    path: {{{ aide_conf_path }}}
    line: database=file:{{{ aide_db_path }}}
    create: true
  when: database_replace.found == 0

- name: "{{{ rule_title }}} - Ensure the Default Out Path is Added"
  ansible.builtin.lineinfile:
    path: {{{ aide_conf_path }}}
    line: database_out=file:{{{ aide_db_new_path }}}
    create: true
  when: database_out_replace.found == 0

- name: "{{{ rule_title }}} - Build and Test AIDE Database"
  ansible.builtin.command: /usr/sbin/aideinit -y -f
